### ISSUE TITLE
Allow picking from a list of location link types

### ISSUE THREAD

**Issue by pierre-guillot** [pR0Ps/LocationShare#10]
Hello,

Why not use OpenStreetMap to share location? Thus LocationShare will be à full Open Source Application :)
Or, add an option to choose between one of them.
URL Exemple for OpenStreeMap : https://www.openstreetmap.org/?mlat=51.51368&mlon=-0.09973#map=19/51.51368/-0.09973

**Comment by tristan-k** [comment]
+1

**Comment by jpggithub** [comment]
+1000 ;-)

**Comment by mahula** [comment]
+1

**Comment by paulle** [comment]
An option for only share coordinates (longitude, latitude) not depending on any app, could also be interesting so users can decide in what app to use it.

**Comment by pR0Ps** [comment]
I'm going to co-opt this issue as a catch-all for different non-customizable services. #4 will handle the custom templates aspect of this.

Right now, my list of choices is:
 - Google Maps: `https://maps.google.com/?q={lat},{lon}`
 - OpenStreetMap [shortlink](http://wiki.openstreetmap.org/wiki/Shortlink): `http://osm.org/go/{data}?m`
    - Normal link would also work: `https://www.openstreetmap.org/?mlat={lat}&mlon={lon}`
 - [Geo URI](https://en.wikipedia.org/wiki/Geo_URI_scheme): `geo:{lat},{lon}`
