### ISSUE TITLE
App stuck at 'Getting Location...'

### ISSUE THREAD

**Issue by Swati4star** [pR0Ps/LocationShare#12]
I opened the app, granted the Location access to it, and its been around 3 minutes, and app is stuck at 'Getting Location..'

**Comment by pR0Ps** [comment]
The application waits until it has a GPS fix before listing the location. If your device has some idea of where it is but can't get a fix, the application will stay at the "Getting Location..." phase.

Is this something you can reproduce in an area where there should be good GPS signal (outside, away from tall buildings, etc)? If so, then there's definitely something going on. If not, I would guess your device was just having a hard time getting a fix. Another thing to test would be if other apps have problems getting a fix too.

**Comment by Swati4star** [comment]
I don't know what the problem is, but it still takes a lot of time at 'Getting Location'

**Comment by sedertreBryst** [comment]
I have the same issue on both my phones (Samsung Galaxy S7 and Huawei P10 Lite). I am going to give it another shot at a different location tomorrow. My accuracy parameter is configured at highest precision on both phones. Other location searching apps like osmand do not have trouble finding me. I really wish I could use the app as an alternative to Google Maps Location sharing... !!

**Comment by sedertreBryst** [comment]
It finally worked. I tried setting my phone with the GPS only option (without Google Location Service) and went on the road. I can see the app is similar to "My position" app on F-Droid.
