### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by boydkelly** [pR0Ps/LocationShare#18]
Hi, Love your app.  I know there is a sea full of these with ads and spyware. Yours is the best.

I do have one feature request.  When you are prompted to choose a link type, could there be a check box to remember this selection and then not have to answer each time?

Thanks

Boyd

**Comment by pR0Ps** [comment]
This would definitely be an improvement and might be the push I need to introduce persistent settings as well as an activity to manage them.

**Comment by mahula** [comment]
I agree with @boydkelly, it is the best and clearest app to exactly just share your location.

@pR0Ps are you already working on this feature's implementation?
I could also contribute, if you want.

**Comment by pR0Ps** [comment]
Closed by 7f18955ac81a21b148f0a31ad49b88b5e5658011
