### ISSUE TITLE
Add an "Ask me everytime" option to the link type options

### ISSUE THREAD

**Issue by pR0Ps** [pR0Ps/LocationShare#22]
- Default the setting to "Ask me every time"
- When sharing, if "Ask me every time" is set, provide a link type chooser (the behavior before #10 was implemented)

**Comment by mahula** [comment]
Wouldn't it be more consistent - with the preferences set to "Ask me **every** time", when sharing not to change the preferences by the user's choice form the provided link choice dialog, but to just proceed to share the location the way the user chose on the spot?
