### ISSUE TITLE
Copy of your app on Google Play (Copyleft violation)

### ISSUE THREAD

**Issue by Poussinou** [pR0Ps/LocationShare#25]
Hi @pR0Ps 

I found [this app](https://play.google.com/store/apps/details?id=ca.swagselfie.locationshare) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by pR0Ps** [comment]
Hi @Poussinou, thanks for the heads up!

It's kind of a dick move, but I fully support their right to release an ad-filled copy of this app, as long as they honor the terms of the license.

I sent an email to the address listed on the app and added a review on the Play Store telling them that they need to comply with the terms of the license. Realistically I don't think that's going to affect anything but I can at least give them a week or so to fix it before asking Google to step in and remove the app.

**Comment by Poussinou** [comment]
I totally agree with what you're doing, I don't have anything against forks who are respecting the license!
As you say, most of the time they don't answer to that kind of mail, but you're doing it right :)

**Comment by pR0Ps** [comment]
The developer did not respond after a week so I asked Google remove it form the store (they did).

**Comment by pR0Ps** [comment]
I do when logged in, but if I use a private session it's gone. I assume it's only visible to people that have downloaded it already.
