### ISSUE TITLE
Proposal new logo for Location Share App

### ISSUE THREAD

**Issue by rezamusic881** [pR0Ps/LocationShare#28]
Hi admin, I want to offer a new logo design is more sweet and simple for application Location Share If you like and can accept it.

You can simply reply to this proposal, I will gladly send you a new logo this file and I was able to provide some variation for this app, thank you!

![s l](https://user-images.githubusercontent.com/37515077/41204941-9353e2a6-6d15-11e8-9ccc-492fd77af03d.png)

**Comment by pR0Ps** [comment]
Hi @rezamusic881, I really appreciate you putting your time and effort into mocking up these icons, however I'm not looking to change the icon of the project at this time.
