### ISSUE TITLE
Trigger by text message or email

### ISSUE THREAD

**Issue by Markus00000** [pR0Ps/LocationShare#34]
Location sharing could be triggered if an incoming text message or email contains a certain string. The app would then automatically reply with the current location.

Why?

1. Give trusted persons the ability to locate you, especially in case of emergencies.
2. Locating a misplaced or stolen phone.

([FindMyPhone](https://erikofsweden.blogspot.com/p/findmyphone.html) implemented this partially. Same issue for My Location at https://github.com/gjedeer/mylocation/issues/21.)

**Comment by pR0Ps** [comment]
Sorry, this feature is a bit out of scope for this project. Feel free to fork the code and make a variant that has it though!
