### ISSUE TITLE
Allow setting of custom message

### ISSUE THREAD

**Issue by pR0Ps** [pR0Ps/LocationShare#4]
Currently, the message is just a Google Maps link. Allowing users to specify their own custom template to plug lat+long into would allow them to use other services or customize their message.

**Comment by mahula** [comment]
Do you have any specific customization in mind?
What about providing several templates to the user (e.g., plain lat+long, specifications of other services) in a sub dialog of the choice dialog suggested for #13?

**Comment by pR0Ps** [comment]
@mahula: I made a comment regarding this here: https://github.com/pR0Ps/LocationShare/pull/13#issuecomment-271106580

**Comment by pR0Ps** [comment]
Thinking more about it, I'm not sure adding the settings and other complexity related to it is worth it. With Google Maps (big mapping company), OSM (open mapping), and GeoURI (a generic protocol), I think the bases are pretty much covered. Any other decent mapping application should be able to parse those links anyway.

If people *really* need an application that has other options, it's dead easy to add them in the XML and compile it themselves (or submit a 2-line PR).
