### ISSUE TITLE
[Feature Request]: Add a "raw" coordinates format 

### ISSUE THREAD

**Issue by brunetton** [pR0Ps/LocationShare#40]
Hi, I just discovered this super simple app that is almost what I wanted to code. I love the option of remembering the favorite default format. This is great for beginners.

But I'd like to be able to share the most simple, and international format: the format I'd call "raw", or "decimal" ie the format that all GPS devices and all maps applications other the world understands: `dd.ddddd, dd.ddddd`. In other words, this is the GeoURI without `geo:` at the beginning.

Would you be opened to a Pull Request adding this option ?

Thanks!

**Comment by pR0Ps** [comment]
Yeah, for sure!

**Comment by pR0Ps** [comment]
Fixed in 52121382dd73571765273c5c77993a9870df5c20

**Comment by brunetton** [comment]
Thank you ! This is very appreciated !
