### ISSUE TITLE
Update F-droid version / publish apk on Githib ?

### ISSUE THREAD

**Issue by brunetton** [pR0Ps/LocationShare#41]
Hi

I'm not sure how f-droid version update works but I've a smartphone that is privated from google services (so play store) and I'd love to use the last version.

Do you have a kind of script (non commited I suppose, I didn't seen it on the repo) that is responsible for the F-droid version update ? Or is it a manual process ? Maybe I can help ? 

It would also be great (more than that!) to be able to download APK directly from [releases](https://github.com/pR0Ps/LocationShare/releases) page.

Thanks a lot !

**Comment by pR0Ps** [comment]
It's an automatic process on F-Droid's side that can sometimes take a while. I'll ping the F-Droid devs if it's not built automatically in a few days.

I'll leave this issue open until it's released.

**Comment by brunetton** [comment]
Thanks, sorry for the noise then

**Comment by pR0Ps** [comment]
The F-Droid version is now live, closing this out

**Comment by brunetton** [comment]
> The F-Droid version is now live, closing this out.
> 
> I also added a release to the project that you can download the APK from.

Thanks a lot @pR0Ps, this is wonderful :)
