### ISSUE TITLE
Add insert location manually to be used by foresters

### ISSUE THREAD

**Issue by metemaddar** [pR0Ps/LocationShare#47]
Imagine a helper of forester is in the mountains and sees a hunter or a problem of wild animals. So says the location using walki talki and this app. Then the foresters at forest station, hear it. Now they need to convert the decimal and open in map apps.

Maybe we could teach them to use geo:DEC
Another easier way, is to have a button to insert geo by hand and then open it in apps.

So we need an inser button and then, open in map button in that view.

**Comment by pR0Ps** [comment]
I'm not sure that this app is the right place for this. This app is more for just an easy way to get your current location. The actual sharing/viewing of that location is delegated to other apps.

A map application that directly supports the decimal format would probably fit your use case better as you could just enter the coordinates into it without having to go through another app. For example, by looking at [OsmAnd's documentation](https://docs.osmand.net/en/main@latest/osmand/plan-route/coordinate-input), it seems like your use case is already supported by it.
