### ISSUE TITLE
Location share not available on Google play store anymore? 

### ISSUE THREAD

**Issue by brunetton** [pR0Ps/LocationShare#49]
Hi

## Short story 

The app is not available in Google play store anymore (at least using the link on the project's description in Github). I tried searching by keyword but didn't found it neither. Did I miss something? 

## Long story 

I'm a big fan of Location Share. I'm speaking of it to everyone, and I certainly think those simple sharing tools should be teach in schools (as well as the open source philosophy... But this is another story).
So, I'm telling anyone about this soft, and as people are not using F-Droid as I obviously do, I share the Google play link (in the project description). But recently the link stopped to work. Do you still want to publish this soft in Google Store ? Or did you changed your mind about it ? 

Thanks a lot

**Comment by brunetton** [comment]
@pR0Ps? I'm not far from forking to make it published on Google store!

Thanks

**Comment by pR0Ps** [comment]
Google removed it from the Play Store about a month ago for what feels like the millionth time for some BS reason. At the time I just couldn't be bothered to fix it and totally forgot about it. I'll take a look at getting it republished soon.

If you would like to publish it yourself, you're more than welcome to (as long as you comply with the licence).

**Comment by pR0Ps** [comment]
It should now be back in the Play Store

**Comment by brunetton** [comment]
Perfect ! Thanks a lot. Hope this'll stay in place
