### ISSUE TITLE
Publish on F-Droid.org

### ISSUE THREAD

**Issue by BoBeR182** [pR0Ps/LocationShare#7]
Can you submit a copy of your application to the f-droid repositories?

**Comment by pR0Ps** [comment]
I will eventually, but at this point I don't feel it's quality is good enough to publicly release.

**Comment by pR0Ps** [comment]
In progress: https://gitlab.com/fdroid/fdroiddata/merge_requests/1803

**Comment by pR0Ps** [comment]
Done: https://f-droid.org/repository/browse/?fdid=ca.cmetcalfe.locationshare
